after-login-command = ['workspace 1']
after-startup-command = ['workspace 1']

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

gaps.outer.top = 0
gaps.outer.bottom = 0
gaps.outer.right = 0
gaps.outer.left = 0
gaps.inner.horizontal = 0
gaps.inner.vertical = 0

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-ctrl-h = 'move left'
alt-ctrl-j = 'move down'
alt-ctrl-k = 'move up'
alt-ctrl-l = 'move right'

alt-ctrl-minus = 'resize smart -50'
alt-ctrl-equal = 'resize smart +50'

alt-ctrl-shift-minus = 'resize smart -200'
alt-ctrl-shift-equal = 'resize smart +200'

alt-0 = 'workspace 0'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-s = 'workspace S'

alt-ctrl-1 = 'move-node-to-workspace 1'
alt-ctrl-0 = 'move-node-to-workspace 0'
alt-ctrl-2 = 'move-node-to-workspace 2'
alt-ctrl-3 = 'move-node-to-workspace 3'
alt-ctrl-4 = 'move-node-to-workspace 4'
alt-ctrl-5 = 'move-node-to-workspace 5'
alt-ctrl-6 = 'move-node-to-workspace 6'
alt-ctrl-7 = 'move-node-to-workspace 7'
alt-ctrl-8 = 'move-node-to-workspace 8'
alt-ctrl-9 = 'move-node-to-workspace 9'
alt-ctrl-s = 'move-node-to-workspace S'
alt-ctrl-m = 'move-workspace-to-monitor --wrap-around next'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-ctrl-semicolon = 'mode service'

cmd-h = []
cmd-m = []

[mode.service.binding]
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
esc = ['reload-config', 'mode main']
alt-ctrl-h = ['join-with left', 'mode main']
alt-ctrl-j = ['join-with down', 'mode main']
alt-ctrl-k = ['join-with up', 'mode main']
alt-ctrl-l = ['join-with right', 'mode main']

[workspace-to-monitor-force-assignment]
S = 'secondary'

[[on-window-detected]]
if.app-id = 'com.apple.clock'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.tdesktop.Telegram'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.FaceTime'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.findmy'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.AppStore'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = ['layout floating']
