after-startup-command = ['exec-and-forget sketchybar']

start-at-login = true

exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 32

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# move mouse center of monitor, and window
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# gaps between tiles
[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# wrap windows focus
alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

alt-f = 'fullscreen'

alt-ctrl-h = 'move left'
alt-ctrl-j = 'move down'
alt-ctrl-k = 'move up'
alt-ctrl-l = 'move right'

alt-ctrl-minus = 'resize smart -50'
alt-ctrl-equal = 'resize smart +50'

alt-ctrl-shift-minus = 'resize smart -200'
alt-ctrl-shift-equal = 'resize smart +200'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 0'

alt-q = 'workspace Q'
alt-w = 'workspace W'
alt-e = 'workspace E'
alt-r = 'workspace R'
alt-t = 'workspace T'
alt-y = 'workspace Y'
alt-u = 'workspace U'
alt-i = 'workspace I'
alt-o = 'workspace O'
alt-p = 'workspace P'

alt-ctrl-1 = 'move-node-to-workspace 1'
alt-ctrl-2 = 'move-node-to-workspace 2'
alt-ctrl-3 = 'move-node-to-workspace 3'
alt-ctrl-4 = 'move-node-to-workspace 4'
alt-ctrl-5 = 'move-node-to-workspace 5'
alt-ctrl-6 = 'move-node-to-workspace 6'
alt-ctrl-7 = 'move-node-to-workspace 7'
alt-ctrl-8 = 'move-node-to-workspace 8'
alt-ctrl-9 = 'move-node-to-workspace 9'
alt-ctrl-0 = 'move-node-to-workspace 0'

alt-ctrl-q = 'move-node-to-workspace Q'
alt-ctrl-w = 'move-node-to-workspace W'
alt-ctrl-e = 'move-node-to-workspace E'
alt-ctrl-r = 'move-node-to-workspace R'
alt-ctrl-t = 'move-node-to-workspace T'
alt-ctrl-y = 'move-node-to-workspace Y'
alt-ctrl-u = 'move-node-to-workspace U'
alt-ctrl-i = 'move-node-to-workspace I'
alt-ctrl-o = 'move-node-to-workspace O'
alt-ctrl-p = 'move-node-to-workspace P'

alt-tab = 'workspace-back-and-forth'

cmd-h = []
cmd-m = []

alt-ctrl-semicolon = 'mode service'

[mode.service.binding]
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
esc = ['reload-config', 'mode main', 'exec-and-forget sketchybar --reload']
alt-ctrl-h = ['join-with left', 'mode main']
alt-ctrl-j = ['join-with down', 'mode main']
alt-ctrl-k = ['join-with up', 'mode main']
alt-ctrl-l = ['join-with right', 'mode main']

[workspace-to-monitor-force-assignment]
6 = 'secondary'
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'
0 = 'secondary'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = ['move-node-to-workspace Q']

[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = ['move-node-to-workspace I']

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = ['move-node-to-workspace O']

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = ['move-node-to-workspace P']

[[on-window-detected]]
if.app-id = 'com.colliderli.iina'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.FaceTime'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['move-node-to-workspace 0']
